version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
      
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
        - db
    ports:
        - "5555:80"
    environment:
        PGADMIN_DEFAULT_EMAIL: homescript1@gmail.com
        PGADMIN_DEFAULT_PASSWORD: timenodey
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
